spring.application.name=neo4j_db

spring.neo4j.uri=neo4j+s://799717da.databases.neo4j.io
spring.neo4j.authentication.username=799717da
spring.neo4j.authentication.password=od_LM4w5rgisMKHPoyU9ZAAFtbC-89EuDjPsI0Vkk6E